var Europa18 = 4209.3;
var Australien18 = 2100.5;
var Asien18 = 16274.1;
var SüdAmerica18 = 1261.5;
var NordAmerica18 = 6035.6;
var Africa18 = 1235.5;
var Europa08 = 4965.7;
var Australien08 = 1993;
var Asien08 = 12954.7;
var SüdAmerica08 = 1132.6;
var NordAmerica08 = 6600.4;
var Africa08 = 1028;
var Total = (Europa18 + Australien18 + Asien18 + SüdAmerica18 + NordAmerica18 + Africa18);
console.log(Total);
var europeRel = Math.round(Europa18 / Total * 100);
var australiaRel = Math.round(Australien18 / Total * 100);
var asiaRel = Math.round(Asien18 / Total * 100);
var southAmericaRel = Math.round(SüdAmerica18 / Total * 100);
var northAmericaRel = Math.round(NordAmerica18 / Total * 100);
var africaRel = Math.round(Africa18 / Total * 100);
var europeGrow = Math.round(Europa18 / Europa08 * 100);
var australiaGrow = Math.round(Australien18 / Australien08 * 100);
var asiaGrow = Math.round(Asien18 / Asien08 * 100);
var southAmericaGrow = Math.round(SüdAmerica18 / SüdAmerica08 * 100);
var northAmericaGrow = Math.round(NordAmerica18 / NordAmerica08 * 100);
var africaGrow = Math.round(Africa08 / Africa18 * 100);
var europeMinus = Math.round(Europa18 - Europa08);
var australiaMinus = Math.round(Australien18 - Australien08);
var asiaMinus = Math.round(Asien18 - Asien08);
var southAmericaMinus = Math.round(SüdAmerica18 - SüdAmerica08);
var northAmericaMinus = Math.round(NordAmerica18 - NordAmerica08);
var africaMinus = Math.round(Africa18 - Africa08);
function myFunctionE(continent, emissions18, emissionsRel, emissionsGrow, emissionsMinus) {
    document.querySelector("h1").innerHTML = "Carbon Dioxide Emissions in " + continent;
    document.querySelector("p").innerHTML = "Emission absolute of " + continent + " in 2018";
    document.querySelector("h2").innerHTML = emissions18;
    document.querySelector("#h22").innerHTML = emissionsRel + "%";
    document.querySelector("#h23").innerHTML = emissionsGrow + "%";
    document.querySelector("#h24").innerHTML = emissionsMinus + "kg CO2";
    document.querySelector(".chart").setAttribute('style', 'height:' + (emissions18 / Total * 100) + '%');
}
document.querySelector(".europe").addEventListener("click", myFunctionE.bind(null, "Europe", Europa18, europeRel, europeGrow, europeMinus));
document.querySelector(".northamerica").addEventListener("click", myFunctionE.bind(null, "North America", NordAmerica18, northAmericaRel, northAmericaGrow, northAmericaMinus));
document.querySelector(".southamerica").addEventListener("click", myFunctionE.bind(null, "South America", SüdAmerica18, southAmericaRel, southAmericaGrow, southAmericaMinus));
document.querySelector(".africa").addEventListener("click", myFunctionE.bind(null, "Africa", Africa18, africaRel, africaGrow, africaMinus));
document.querySelector(".asia").addEventListener("click", myFunctionE.bind(null, "Asia", Asien18, asiaRel, asiaGrow, asiaMinus));
document.querySelector(".australia").addEventListener("click", myFunctionE.bind(null, "Australia", Australien18, australiaRel, australiaGrow, australiaMinus));
//# sourceMappingURL=06_script.js.map